<a href="https://colab.research.google.com/github/PECO-chan/Keras-book-practice/blob/master/copy_chap2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.datasets import mnist

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [9]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**NN例**

In [0]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation="relu", input_shape=(28*28,)))
network.add(layers.Dense(10, activation="softmax"))

In [0]:
network.compile(optimizer="rmsprop",
                loss="categorical_crossentropy",
                metrics=["accuracy"])

In [0]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype("float32") / 255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype("float32") / 255

In [0]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [14]:
network.fit(train_images, train_labels, epochs=5, batch_size = 128)

Epoch 1/5
60000/60000 [==============================] - 6s 99us/step - loss: 0.2535 - acc: 0.9267
Epoch 2/5
60000/60000 [==============================] - 5s 86us/step - loss: 0.1032 - acc: 0.9696
Epoch 3/5
60000/60000 [==============================] - 5s 85us/step - loss: 0.0675 - acc: 0.9798
Epoch 4/5
60000/60000 [==============================] - 5s 84us/step - loss: 0.0493 - acc: 0.9854
Epoch 5/5
60000/60000 [==============================] - 5s 85us/step - loss: 0.0370 - acc: 0.9885


In [15]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print("test_acc: ", test_acc)

10000/10000 [==============================] - 1s 53us/step
test_acc:  0.9799


**いろいろ基礎**

In [16]:
import numpy as np
x = np.array(12)
x

array(12)

In [17]:
x.ndim

0

In [19]:
x = np.array([12,3,6,14,7])
x

array([12,  3,  6, 14,  7])

In [20]:
x.ndim

1

In [21]:
x = np.array([[5,78,2,34,0],
             [6,79,3,35,1],
             [7,89,4,36,2]])
x.ndim

2

In [23]:
x = np.array([
    
             [
              [5,78,2,34,0],
              [6,79,3,35,1],
              [7,89,4,36,2]
                           ],
             [
              [5,78,2,34,0],
              [6,79,3,35,1],
              [7,89,4,36,2]
                           ],
             [
              [5,78,2,34,0],
              [6,79,3,35,1],
              [7,89,4,36,2]
                           ]
    ])
x.ndim

3

In [0]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()